### ISSUE TITLE
Build problem: wrong maven dependencies

### ISSUE THREAD

**Issue by mbrodowski** [berndruecker/flowing-retail#1]
Hi,
I'm trying to build this project but some problem with dependencies rised.
1.  Order and Payment modules use `<camunda.version>7.7.3-ee</camunda.version>` but this version doesn't exist in public repository
I've solved problem changing version to
<camunda.version>7.7.0</camunda.version>

2. These modules use 
```
<dependency>
			<groupId>com.camunda.consulting.webapp</groupId>
			<artifactId>camunda-webapp-customized-webjar</artifactId>
			<version>7.7.2</version>
			<scope>provided</scope>
		</dependency>
```
this dependecy include another dependency which not exists
```
<dependency>
      <groupId>org.camunda.bpm.webapp</groupId>
      <artifactId>camunda-webapp-ee-plugins</artifactId>
      <version>7.7.2-ee</version>
      <type>jar</type>
      <classifier>classes</classifier>
    </dependency>
```
I've solved this problem removing this dependency camunda-webapp-ee-plugins from pom

**Comment by codeongit** [comment]
this project use ee version of camunda by default.  just check the comment in the pom. you will find the answer.

**Comment by berndruecker** [comment]
Sorry for that - accidentially commited. Fixed by https://github.com/flowing/flowing-retail/commit/8af6e6bb0497817ac2a0498e5a71d06572e4a5f8
