### ISSUE TITLE
Recieved Warning while running sample

### ISSUE THREAD

**Issue by dmarhas** [berndruecker/flowing-retail#17]
Can there warnings be ignored? I just followed the instructions and the sample seems to be running.

WARN 17168 --- [container-0-C-1] .DispatchingStreamListenerMessageHandler : Cannot find a @StreamListener matching for message with id: null

**Comment by berndruecker** [comment]
It can - as I just used one Kafka topic for everything there are a lot of messges ignored by various services. Nothing to worry about
