### ISSUE TITLE
Problem with Jersey on Order Camunda microservice

### ISSUE THREAD

**Issue by damageco** [berndruecker/flowing-retail#18]
Hello,
 I've tried to start the Order Camunda microservice with mvn -f order-camunda exec:java but I've got the following error :

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project flowing-retail-kafka-order-camunda: An exception occured while executing the Java class. Error processing condition on org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat: Failed to introspect Class [org.camunda.bpm.spring.boot.starter.rest.CamundaBpmRestJerseyAutoConfiguration] from ClassLoader [java.net.URLClassLoader@6e5c9a5d]: javax/ws/rs/core/Configurable: javax.ws.rs.core.Configurable

I needed to add the Jersey librairie dependancy in pom.xml with : 
<dependency>
	<groupId>javax.ws.rs</groupId>
	<artifactId>javax.ws.rs-api</artifactId>
	<version>2.1.1</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-common</artifactId>
	<version>2.28</version>
</dependency>

**Comment by berndruecker** [comment]
@damageco : Which Java version are you using?

**Comment by berndruecker** [comment]
Closing as @damageco is not responding - making it hard to investigate. Please reopen with more details if you still face issues!
