### ISSUE TITLE
search zeebe create instance command

### ISSUE THREAD

**Issue by pcouas** [berndruecker/flowing-retail#21]
Hi,

I search zbctl complete create instance command
I hve tried without succes
\zbctl.exe create instance order-zeebe --variables "{\"orderId\": \"1234\", \"orderValue\":99}"

Regards

**Comment by berndruecker** [comment]
What's the exact problem you are facing? The command seems to be right - I also double checked with the docs: https://docs.zeebe.io/introduction/quickstart.html#step-4-create-a-workflow-instance and the source: https://github.com/zeebe-io/zeebe/blob/develop/clients/zbctl/cmd/createInstance.go. Please re-open with the complete error message and scenario description. thanks.
