### ISSUE TITLE
Can't find event handler for Payment RetrievePaymentCommand event

### ISSUE THREAD

**Issue by marcusfaoro** [berndruecker/flowing-retail#22]
Hi there,
This application doesn't work. I can receive an Order "OrderPlacedEvent" after posting an Order via Checkout Service, however the Payment Service is never triggered.

I'm running:
-Local Zeebe (zeebe-broker-0.20.0);
-Local Kafka (kafka_2.12-2.2.0)
-Java 8

Thanks,
Marcus

**Comment by berndruecker** [comment]
Sorry for the delay, better ping me via Twitter or Email instead. Which "Payment" service do you start? The choreographed one should actually be triggered right away, the orchestrated only reacts to a command, and therefor you have to start one of the order microservices. Hope that helps?

**Comment by marcusfaoro** [comment]
Hi Bern,

I'm running the solution which is a mix of Choreography and Orchestration. It uses Kafka and Zeebe.

Steps:
1. Started Kafka
2. Started Zeebe
3. Started the Microservices 
   - checkout, inventory, monitor, payment, shipping, order-zeebe
4. I created and order via the Checkout service however it never made through the Payment service. I'm not sure the problem is in the Subscriber or something
   but that code is not working

Thanks Bern

**Comment by berndruecker** [comment]
Does order-zeebe works? Can you see the workflow being kicked off in Zeebe (e.g. using Operate)? Does it send out the "retrieve-payment-command"?

**Comment by marcusfaoro** [comment]
Hi Bern,

No, it doesn't, that's why I started this threat.

The OrderService listeners are not reached and the monitor also doesnt show
the workflow moving on.

Thank you



Em ter, 15 de out de 2019 às 23:57, Bernd Rücker <notifications@github.com>
escreveu:
