### ISSUE TITLE
Remote Camunda Kafka usage

### ISSUE THREAD

**Issue by meenarc** [berndruecker/flowing-retail#25]
Was looking through the use cases here where the examples show how to use the embedded camunda to talk to Kafka

We have a use case where a remote Camunda cluster would be used for service orchestration across multiple use cases.
In such cases we would have a flow where the remote service may send/receive messages to the event bus and remote Camunda would need to process these messages..
Also the same or diff workflow can talk to different kafka topics and send /receive diff events 
What are the options in such cases when designing the workflow?

i)Send task to send messages?
iiReceive task-but can we receive messages from diff topics within the same workflow?How do we handle kafka topic offset reset in case of retries etc in such cases?
iii) Have a customized service task to handle kafka communication , deployed in the remote engine ? This lets us throw in some JSON customization,error handling etc . This approach is sort of what we are leaning towards now. 

iv)Create a custom kafka connector?

**Comment by berndruecker** [comment]
Hey @meenarc - as this is not an issue I moved it to the forum to answer it there: https://forum.camunda.org/t/remote-camunda-kafka-usage/18565
