### ISSUE TITLE
Order & Payment doesn't run

### ISSUE THREAD

**Issue by lsantaniello** [berndruecker/flowing-retail#3]
I execute the commands:

mvn -f order exec:java -D exec.mainClass="io.flowing.retail.order.OrderApplication"
mvn -f payment exec:java -D exec.mainClass="io.flowing.retail.payment.PaymentApplication"

Caused by: javax.servlet.ServletException: Could not read security filter config file '/securityFilterRules.json': no such resource in servlet context.

The microservice doesn't start.

Help me please

**Comment by berndruecker** [comment]
I cannot reproduce this in the current master. Could you probably quickly check if the error is still there with the latest master? 

Seems to be a weird issue though (see also https://github.com/camunda/camunda-bpm-spring-boot-starter/issues/158). I will update the Spring Boot Starter to the upcoming release in two weeks - we improved it a lot so I am pretty confident that at least that will fix it!

**Comment by ccristian** [comment]
I don't have that anymore neither ...

**Comment by berndruecker** [comment]
Just as a remark, this might be seen if Camunda and Spring Boot Starter version does not fit: https://docs.camunda.org/manual/7.10/user-guide/spring-boot-integration/version-compatibility/
