### ISSUE TITLE
registry.camunda.cloud/camunda-bpm-platform-ee:7.12.1

### ISSUE THREAD

**Issue by MrBambix** [berndruecker/flowing-retail#40]
Hi,

Currently on using docker compose i get authorization errors on pulling: registry.camunda.cloud/camunda-bpm-platform-ee:7.12.1 can you please investigate?

Thank you and regards,
Leo de Blaauw

**Comment by berndruecker** [comment]
Please use 7.12.0 - as this is the community edition. 7.12.1 is the EE version which is only available with login. Note that 7.12 is also a bit - please update to the latest version (7.14.0).

Is 7.12.1 linked somewhere in the code? Please let me know where exactly, so I can fix this. I also create an issue to update to the latest Camunda version

**Comment by berndruecker** [comment]
https://github.com/berndruecker/flowing-retail/issues/41

**Comment by MrBambix** [comment]
This is the offending line:

File: docker-compose-kafka-camunda-optimize.yml
cambpm:
    image: registry.camunda.cloud/camunda-bpm-platform-ee:7.12.1

File:docker-compose-kafka-java-choreography-camunda-optimize.yml
 cambpm:
    image: registry.camunda.cloud/camunda-bpm-platform-ee:7.12.1

**Comment by MrBambix** [comment]
The exact error is below, regardless of setting the BPM platform to a higher/lower version:

D:\flowing-retail-master\runner\docker-compose> docker-compose -f .\docker-compose-kafka-java-choreography-camunda-optimize.yml up -d
Pulling cambpm (registry.camunda.cloud/camunda-bpm-platform-ee:7.12.0)...
ERROR: unauthorized: unauthorized to access repository: cambpm-ee/camunda-bpm-platform-ee, action: pull: unauthorized to access repository: cambpm-ee/camunda-bpm-platform-ee, action: pull

Regards,
Leo

**Comment by berndruecker** [comment]
You need to pull "registry.camunda.cloud/camunda-bpm-platform:7.12.0" (remove the "-ee").

But please note that you can't use Optimize without enterprise license / account - so you might need to use another docker compose fial. If you want exactly this to also use Optimize, a trial license does suffice: https://camunda.com/download/enterprise/. There you get credentials to log on onto our registry to be able to also get the EE artefacts

**Comment by MrBambix** [comment]
@berndruecker what i was trying to do was to run your examples on microservices with the docker images ;-)

**Comment by MrBambix** [comment]
> You need to pull "registry.camunda.cloud/camunda-bpm-platform:7.12.0" (remove the "-ee").
> 
> But please note that you can't use Optimize without enterprise license / account - so you might need to use another docker compose fial. If you want exactly this to also use Optimize, a trial license does suffice: https://camunda.com/download/enterprise/. There you get credentials to log on onto our registry to be able to also get the EE artefacts

@berndruecker 
I have registered for a Camunda EE trial licence and got the licence key in the mail. But how does that enable me to download a docker EE image from your registry ?

regards,
Leo

**Comment by berndruecker** [comment]
You need to add the credentials to Maven as described here: https://docs.camunda.org/get-started/apache-maven/#enterprise-edition-1. 

Sorry for the confusion - I should clean this up a bit and describe what's necessary to play around with Optimize

**Comment by MrBambix** [comment]
> You need to add the credentials to Maven as described here: https://docs.camunda.org/get-started/apache-maven/#enterprise-edition-1.
> 
> Sorry for the confusion - I should clean this up a bit and describe what's necessary to play around with Optimize

@berndruecker ah so you are saying the docker-compose approach will never work then ? Then maybe remove the docker compose files completely which rely on the EE version of camunda.

greetz
Leo

**Comment by berndruecker** [comment]
No sorry - my fault. You can use the same credentials for the docker login - just copied the wrong link. Can add it later when back to the computer - or you look it up in the docs...

**Comment by berndruecker** [comment]
This is the link you need: https://docs.camunda.org/optimize/latest/technical-guide/setup/installation/#production-docker-image-without-elasticsearch

**Comment by MrBambix** [comment]
> This is the link you need: https://docs.camunda.org/optimize/latest/technical-guide/setup/installation/#production-docker-image-without-elasticsearch

thank you, yes got it working by manually pulling the docker image and then use the docker-compose file to start the total environment. Working great, now onto investigate in what is going with your demo ;-)

Thanks and greetings,
Leo
