### ISSUE TITLE
No such host is known (<Cluster Id>.zeebe.camunda.io)

### ISSUE THREAD

**Issue by sabriGit** [berndruecker/flowing-retail#59]
Hello,
When trying to run this example: I got the following error :
Steps done: 
- application.properties in all microservices was updated with the right credentials obtained from Camunda Cloud console.
- mvn -f checkout exec:java
Error :
"Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host .."

@berndruecker , Thanks in advance for your help.

**Comment by berndruecker** [comment]
Hi @sabriGit. Good catch. You need to update the Zeebe client to >= 1.1.0 in the pom.xml, as Camunda Cloud introduced regions. 

```
<dependency>
	<groupId>io.camunda</groupId>
	<artifactId>spring-zeebe-starter</artifactId>
	<version>1.1.0</version>
</dependency>
```

**Comment by berndruecker** [comment]
https://github.com/berndruecker/flowing-retail/issues/60

**Comment by sabriGit** [comment]
Hi @berndruecker, 
Thank you, it resolves the issue.
