### ISSUE TITLE
Kafka Docker Example Performance 

### ISSUE THREAD

**Issue by 1123** [berndruecker/flowing-retail#82]
Great Tutorial and Use Case. This shows clearly the benefit of a distributed workflow engine. 

While testing the performance in the local setup, I noticed that the system is already at a limit with 10 orders per second. Clearly in a production environment, services would be distributed across separate VMs, and possibly also scaled horizontally for fault tolerance. Still it seems like there is a clear bottleneck in the Zeebe service writing data to ElasticSearch, and one would expect a performance of more than 10 workflows / second even in a sample setup. While all other services have done their job, the logs of Zeebe still show write requests to Elastic. 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/3542487/200166004-ff02e307-809f-4fa6-a89b-51a5c1d9016f.png">

This results in Camunda Operate showing out of date information when it comes to the state of the workflow instances: 

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/3542487/200166037-a0b34687-80ea-4e1a-94a5-076a20e4861e.png">

Wouldn't it be possible to batch the writes from Zeebe to ElasticSearch to improve the performance by quite a bit? Or Is batching already taking place? Why are the writes so slow?

**Comment by berndruecker** [comment]
I am closing this if you don't mind - I think if you want to look at performance you should use a normal Camunda 8 distro and test there (and ideally ask in the forum then if there are any issues: https://forum.camunda.io/.

OK?
